### ISSUE TITLE
Where modify search form / post ad form

### ISSUE THREAD

**Issue by didi110296** [inoks/django-classified#31]
Hello,
i'm beginner in python and i have searched how to modify search form and post form for change the style but nothing...
Apparently these two forms were written in python.
If you can give me help pls, thx.
If possible i want edit the html code in link with these forms.

**Comment by inoks** [comment]
Hi @didi110296 !
You can modify the [search template](https://github.com/inoks/django-classified/blob/master/django_classified/templates/django_classified/search.html) in order to change how it looks.
Serach form rendered using [Django Bootstrap Form](https://django-bootstrap-form.readthedocs.io/en/latest/) package.
Let me know if it helps.
